### ISSUE TITLE
no method to post data?

### ISSUE THREAD

**Issue by streamnsight** [OwnLocal/goes#2]
is there a way to post data to Elasticsearch?
Looking at the code, I don't see it, but maybe I'm missing something.

**Comment by pib** [comment]
There are two ways to index documents into ES.

The first is to use the [Index method](https://github.com/OwnLocal/goes/blob/master/goes.go#L311) (see the [Elasticsearch Index docs](https://www.elastic.co/guide/en/elasticsearch/reference/1.7/docs-index_.html) for more information on usage).

The other is to use the [BulkSend method](https://github.com/OwnLocal/goes/blob/master/goes.go#L133) (see the [Elasticsearch Bulk API docs](https://www.elastic.co/guide/en/elasticsearch/reference/1.7/docs-bulk.html) for more info).
